import Head from 'next/head';
import MenuButton from '@/components/MenuButton';
import { Center } from '@mantine/core';

export default function Home() {
  return (
    <>
      <Head>
        <title>IOTPB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-2">

        <MenuButton text={"Login"}></MenuButton>
        <MenuButton text={"Sign Up"}></MenuButton>

      </div>

    </>
  )
}
